apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-app
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://okelolalekan2019:adeleke2019@cluster0.4tpg3xo.mongodb.net/TodoApp?retryWrites=true&w=majority&appName=ChatAn"

